const API_URL_BASE = "/api/v1" as const;

export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  CHANGE_PASSWORD: "/auth/change-password",
  REGISTER_EMPLOYEE: "/auth/register-employee",
  TASK_LIST: "/tasks",
  TASK: "/tasks/:id",
  SET_TASK: "/tasks/set",
  SEND_MESSAGE: "/messages/send",
  PROJECT_LIST: "/projects",
  PROJECT: "/projects/:id",
  CREATE_PROJECT: "/projects/create",
  EDIT_PROJECT: "/projects/edit/:id",
  API_LOGIN: `${API_URL_BASE}/auth/login`,
  API_LOGOUT: `${API_URL_BASE}/auth/logout`,
  API_CHANGE_PASSWORD: `${API_URL_BASE}/auth/change-password`,
  API_REGISTER_EMPLOYEE: `${API_URL_BASE}/auth/register-employee`,
  API_SET_TASK: `${API_URL_BASE}/tasks`,
  API_GET_RELATED_TASKS: `${API_URL_BASE}/tasks/related`,
  API_UPDATE_TASK_STATUS: `${API_URL_BASE}/tasks/status`,
  API_GET_RELATED_PROJECTS: `${API_URL_BASE}/projects/related`,
  API_SEND_MESSAGE: `${API_URL_BASE}/messages/send`,
  API_CREATE_PROJECT: `${API_URL_BASE}/projects`,
  API_EDIT_PROJECT: `${API_URL_BASE}/projects/edit`,
} as const;
