const API_URL_BASE = "/api/v1" as const;

export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  CHANGE_PASSWORD: "/auth/change-password",
  REGISTER_EMPLOYEE: "/auth/register-employee",
  PROGRESS_LIST: "/tasks",
  PROGRESS: "/tasks/:id",
  SEND_PROGRESS: "/tasks/set",
  EXTEND_PROGRESS: "/tasks/extend",
  PROJECT_LIST: "/projects",
  PROJECT: "/projects/:id",
  CREATE_PROJECT: "/projects/create",
  EDIT_PROJECT: "/projects/edit/:id",
  API_LOGIN: `${API_URL_BASE}/auth/login`,
  API_LOGOUT: `${API_URL_BASE}/auth/logout`,
  API_CHANGE_PASSWORD: `${API_URL_BASE}/auth/change-password`,
  API_REGISTER_EMPLOYEE: `${API_URL_BASE}/auth/register-employee`,
  API_SEND_PROGRESS: `${API_URL_BASE}/tasks`,
  API_GET_RELATED_PROGRESS: `${API_URL_BASE}/tasks/related`,
  API_GET_RELATED_PROJECTS: `${API_URL_BASE}/projects/related`,
  API_EXTEND_PROGRESS: `${API_URL_BASE}/tasks/extend`,
  API_CREATE_PROJECT: `${API_URL_BASE}/projects`,
  API_EDIT_PROJECT: `${API_URL_BASE}/projects/edit`,
} as const;
