drop policy "Enable bosses to see the progress of their projects" on "public"."progress";

drop policy "Enable employees to create progress" on "public"."progress";

drop policy "Enable employees to see the progress of their projects" on "public"."progress";

drop policy "Enable bosses to see the progress media of their projects" on "public"."progress_media";

drop policy "Enable employees to create progress media" on "public"."progress_media";

drop policy "Enable employees to see the progress media of their projects" on "public"."progress_media";

revoke delete on table "public"."progress" from "anon";

revoke insert on table "public"."progress" from "anon";

revoke references on table "public"."progress" from "anon";

revoke select on table "public"."progress" from "anon";

revoke trigger on table "public"."progress" from "anon";

revoke truncate on table "public"."progress" from "anon";

revoke update on table "public"."progress" from "anon";

revoke delete on table "public"."progress" from "authenticated";

revoke insert on table "public"."progress" from "authenticated";

revoke references on table "public"."progress" from "authenticated";

revoke select on table "public"."progress" from "authenticated";

revoke trigger on table "public"."progress" from "authenticated";

revoke truncate on table "public"."progress" from "authenticated";

revoke update on table "public"."progress" from "authenticated";

revoke delete on table "public"."progress" from "service_role";

revoke insert on table "public"."progress" from "service_role";

revoke references on table "public"."progress" from "service_role";

revoke select on table "public"."progress" from "service_role";

revoke trigger on table "public"."progress" from "service_role";

revoke truncate on table "public"."progress" from "service_role";

revoke update on table "public"."progress" from "service_role";

revoke delete on table "public"."progress_media" from "anon";

revoke insert on table "public"."progress_media" from "anon";

revoke references on table "public"."progress_media" from "anon";

revoke select on table "public"."progress_media" from "anon";

revoke trigger on table "public"."progress_media" from "anon";

revoke truncate on table "public"."progress_media" from "anon";

revoke update on table "public"."progress_media" from "anon";

revoke delete on table "public"."progress_media" from "authenticated";

revoke insert on table "public"."progress_media" from "authenticated";

revoke references on table "public"."progress_media" from "authenticated";

revoke select on table "public"."progress_media" from "authenticated";

revoke trigger on table "public"."progress_media" from "authenticated";

revoke truncate on table "public"."progress_media" from "authenticated";

revoke update on table "public"."progress_media" from "authenticated";

revoke delete on table "public"."progress_media" from "service_role";

revoke insert on table "public"."progress_media" from "service_role";

revoke references on table "public"."progress_media" from "service_role";

revoke select on table "public"."progress_media" from "service_role";

revoke trigger on table "public"."progress_media" from "service_role";

revoke truncate on table "public"."progress_media" from "service_role";

revoke update on table "public"."progress_media" from "service_role";

alter table "public"."progress" drop constraint "progress_employee_id_fkey";

alter table "public"."progress" drop constraint "progress_parent_id_fkey";

alter table "public"."progress" drop constraint "progress_project_id_fkey";

alter table "public"."progress" drop constraint "progress_title_description_check";

alter table "public"."progress_media" drop constraint "progress_media_progress_id_fkey";

alter table "public"."progress" drop constraint "progress_pkey";

alter table "public"."progress_media" drop constraint "progress_media_pkey";

drop index if exists "public"."progress_media_pkey";

drop index if exists "public"."progress_pkey";

drop table "public"."progress";

drop table "public"."progress_media";

create table "public"."message" (
    "id" bigint generated by default as identity not null,
    "content" text not null,
    "sent_date" timestamp with time zone not null default now(),
    "task_id" bigint not null,
    "profile_id" uuid not null
);


alter table "public"."message" enable row level security;

create table "public"."message_media" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "type" text not null,
    "url" text not null
);


alter table "public"."message_media" enable row level security;

create table "public"."task" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text not null,
    "start_date" timestamp with time zone not null,
    "duration" bigint not null,
    "completed" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "boss_id" uuid not null
);


alter table "public"."task" enable row level security;

create table "public"."task_assignment" (
    "created_at" timestamp with time zone not null default now(),
    "employee_id" uuid not null,
    "task_id" bigint not null
);


alter table "public"."task_assignment" enable row level security;

create table "public"."task_media" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "task_id" bigint not null,
    "type" text not null,
    "url" text not null
);


alter table "public"."task_media" enable row level security;

CREATE UNIQUE INDEX task_assignment_pkey ON public.task_assignment USING btree (employee_id, task_id);

CREATE UNIQUE INDEX task_media_pkey ON public.task_media USING btree (id);

CREATE UNIQUE INDEX task_pkey ON public.task USING btree (id);

CREATE UNIQUE INDEX progress_media_pkey ON public.message_media USING btree (id);

CREATE UNIQUE INDEX progress_pkey ON public.message USING btree (id);

alter table "public"."message" add constraint "progress_pkey" PRIMARY KEY using index "progress_pkey";

alter table "public"."message_media" add constraint "progress_media_pkey" PRIMARY KEY using index "progress_media_pkey";

alter table "public"."task" add constraint "task_pkey" PRIMARY KEY using index "task_pkey";

alter table "public"."task_assignment" add constraint "task_assignment_pkey" PRIMARY KEY using index "task_assignment_pkey";

alter table "public"."task_media" add constraint "task_media_pkey" PRIMARY KEY using index "task_media_pkey";

alter table "public"."message" add constraint "message_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profile(id) ON DELETE CASCADE not valid;

alter table "public"."message" validate constraint "message_profile_id_fkey";

alter table "public"."message" add constraint "message_task_id_fkey" FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE not valid;

alter table "public"."message" validate constraint "message_task_id_fkey";

alter table "public"."message_media" add constraint "progress_media_progress_id_fkey" FOREIGN KEY (message_id) REFERENCES message(id) ON DELETE CASCADE not valid;

alter table "public"."message_media" validate constraint "progress_media_progress_id_fkey";

alter table "public"."task" add constraint "task_boss_id_fkey" FOREIGN KEY (boss_id) REFERENCES boss(id) ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "task_boss_id_fkey";

alter table "public"."task_assignment" add constraint "task_assignment_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE not valid;

alter table "public"."task_assignment" validate constraint "task_assignment_employee_id_fkey";

alter table "public"."task_assignment" add constraint "task_assignment_task_id_fkey" FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE not valid;

alter table "public"."task_assignment" validate constraint "task_assignment_task_id_fkey";

alter table "public"."task_media" add constraint "task_media_task_id_fkey" FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE not valid;

alter table "public"."task_media" validate constraint "task_media_task_id_fkey";

grant delete on table "public"."message" to "anon";

grant insert on table "public"."message" to "anon";

grant references on table "public"."message" to "anon";

grant select on table "public"."message" to "anon";

grant trigger on table "public"."message" to "anon";

grant truncate on table "public"."message" to "anon";

grant update on table "public"."message" to "anon";

grant delete on table "public"."message" to "authenticated";

grant insert on table "public"."message" to "authenticated";

grant references on table "public"."message" to "authenticated";

grant select on table "public"."message" to "authenticated";

grant trigger on table "public"."message" to "authenticated";

grant truncate on table "public"."message" to "authenticated";

grant update on table "public"."message" to "authenticated";

grant delete on table "public"."message" to "service_role";

grant insert on table "public"."message" to "service_role";

grant references on table "public"."message" to "service_role";

grant select on table "public"."message" to "service_role";

grant trigger on table "public"."message" to "service_role";

grant truncate on table "public"."message" to "service_role";

grant update on table "public"."message" to "service_role";

grant delete on table "public"."message_media" to "anon";

grant insert on table "public"."message_media" to "anon";

grant references on table "public"."message_media" to "anon";

grant select on table "public"."message_media" to "anon";

grant trigger on table "public"."message_media" to "anon";

grant truncate on table "public"."message_media" to "anon";

grant update on table "public"."message_media" to "anon";

grant delete on table "public"."message_media" to "authenticated";

grant insert on table "public"."message_media" to "authenticated";

grant references on table "public"."message_media" to "authenticated";

grant select on table "public"."message_media" to "authenticated";

grant trigger on table "public"."message_media" to "authenticated";

grant truncate on table "public"."message_media" to "authenticated";

grant update on table "public"."message_media" to "authenticated";

grant delete on table "public"."message_media" to "service_role";

grant insert on table "public"."message_media" to "service_role";

grant references on table "public"."message_media" to "service_role";

grant select on table "public"."message_media" to "service_role";

grant trigger on table "public"."message_media" to "service_role";

grant truncate on table "public"."message_media" to "service_role";

grant update on table "public"."message_media" to "service_role";

grant delete on table "public"."task" to "anon";

grant insert on table "public"."task" to "anon";

grant references on table "public"."task" to "anon";

grant select on table "public"."task" to "anon";

grant trigger on table "public"."task" to "anon";

grant truncate on table "public"."task" to "anon";

grant update on table "public"."task" to "anon";

grant delete on table "public"."task" to "authenticated";

grant insert on table "public"."task" to "authenticated";

grant references on table "public"."task" to "authenticated";

grant select on table "public"."task" to "authenticated";

grant trigger on table "public"."task" to "authenticated";

grant truncate on table "public"."task" to "authenticated";

grant update on table "public"."task" to "authenticated";

grant delete on table "public"."task" to "service_role";

grant insert on table "public"."task" to "service_role";

grant references on table "public"."task" to "service_role";

grant select on table "public"."task" to "service_role";

grant trigger on table "public"."task" to "service_role";

grant truncate on table "public"."task" to "service_role";

grant update on table "public"."task" to "service_role";

grant delete on table "public"."task_assignment" to "anon";

grant insert on table "public"."task_assignment" to "anon";

grant references on table "public"."task_assignment" to "anon";

grant select on table "public"."task_assignment" to "anon";

grant trigger on table "public"."task_assignment" to "anon";

grant truncate on table "public"."task_assignment" to "anon";

grant update on table "public"."task_assignment" to "anon";

grant delete on table "public"."task_assignment" to "authenticated";

grant insert on table "public"."task_assignment" to "authenticated";

grant references on table "public"."task_assignment" to "authenticated";

grant select on table "public"."task_assignment" to "authenticated";

grant trigger on table "public"."task_assignment" to "authenticated";

grant truncate on table "public"."task_assignment" to "authenticated";

grant update on table "public"."task_assignment" to "authenticated";

grant delete on table "public"."task_assignment" to "service_role";

grant insert on table "public"."task_assignment" to "service_role";

grant references on table "public"."task_assignment" to "service_role";

grant select on table "public"."task_assignment" to "service_role";

grant trigger on table "public"."task_assignment" to "service_role";

grant truncate on table "public"."task_assignment" to "service_role";

grant update on table "public"."task_assignment" to "service_role";

grant delete on table "public"."task_media" to "anon";

grant insert on table "public"."task_media" to "anon";

grant references on table "public"."task_media" to "anon";

grant select on table "public"."task_media" to "anon";

grant trigger on table "public"."task_media" to "anon";

grant truncate on table "public"."task_media" to "anon";

grant update on table "public"."task_media" to "anon";

grant delete on table "public"."task_media" to "authenticated";

grant insert on table "public"."task_media" to "authenticated";

grant references on table "public"."task_media" to "authenticated";

grant select on table "public"."task_media" to "authenticated";

grant trigger on table "public"."task_media" to "authenticated";

grant truncate on table "public"."task_media" to "authenticated";

grant update on table "public"."task_media" to "authenticated";

grant delete on table "public"."task_media" to "service_role";

grant insert on table "public"."task_media" to "service_role";

grant references on table "public"."task_media" to "service_role";

grant select on table "public"."task_media" to "service_role";

grant trigger on table "public"."task_media" to "service_role";

grant truncate on table "public"."task_media" to "service_role";

grant update on table "public"."task_media" to "service_role";


