revoke delete on table "public"."project_employee" from "anon";

revoke insert on table "public"."project_employee" from "anon";

revoke references on table "public"."project_employee" from "anon";

revoke select on table "public"."project_employee" from "anon";

revoke trigger on table "public"."project_employee" from "anon";

revoke truncate on table "public"."project_employee" from "anon";

revoke update on table "public"."project_employee" from "anon";

revoke delete on table "public"."project_employee" from "authenticated";

revoke insert on table "public"."project_employee" from "authenticated";

revoke references on table "public"."project_employee" from "authenticated";

revoke select on table "public"."project_employee" from "authenticated";

revoke trigger on table "public"."project_employee" from "authenticated";

revoke truncate on table "public"."project_employee" from "authenticated";

revoke update on table "public"."project_employee" from "authenticated";

revoke delete on table "public"."project_employee" from "service_role";

revoke insert on table "public"."project_employee" from "service_role";

revoke references on table "public"."project_employee" from "service_role";

revoke select on table "public"."project_employee" from "service_role";

revoke trigger on table "public"."project_employee" from "service_role";

revoke truncate on table "public"."project_employee" from "service_role";

revoke update on table "public"."project_employee" from "service_role";

alter table "public"."project" drop constraint "project_boss_id_fkey";

alter table "public"."project_employee" drop constraint "project_employee_employee_id_fkey";

alter table "public"."project_employee" drop constraint "project_employee_project_id_fkey";

alter table "public"."task" drop constraint "task_boss_id_fkey";

alter table "public"."project_employee" drop constraint "project_employee_pkey";

drop index if exists "public"."project_employee_pkey";

drop table "public"."project_employee";

alter table "public"."project" drop column "boss_id";

alter table "public"."project" alter column "id" set generated by default;

alter table "public"."task" drop column "boss_id";

alter table "public"."task" add column "project_id" bigint not null;

alter table "public"."task" add constraint "task_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "task_project_id_fkey";


